name: Robot Attic
favicon: null
layout_spectrum: 0.03476147400215268
typography_spectrum: 0.4247246452141553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7928099257405847
  lightness: 0.9693290530703962
  saturation: 0.5062764717731625
  rhythmicContrast: 0.3668786226771772
purpose: []
